security:
  user.password: password
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      stripPrefix: true
    uploader:
      path: /upload**
      url: http://localhost:9001
      stripPrefix: false
    elasticsearch:
      path: /elasticsearch/**
      url: http://localhost:9200
      stripPrefix: true
    mailstore:
          path: /mailstore/**
          url: http://localhost:9100
          stripPrefix: true

server.port: 8080

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  format_sql: true
  hbm2ddl.auto: update

logging:
  level.org.hibernate.SQL: debug
  
#Lpc add
spring:
  application:
     name: web
  autoconfigure:
     exclude: org.springframework.cloud.netflix.servo.ServoMetricsAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/hansight-saas
    username: saas
    password: changeme
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
    prefix: file:saas/

#security.basic.enabled: false
netflix:
  atlas:
    uri: http://localhost:7101/api/v1/publish
  spectator:
    rest:
      maxAge: 2000

eureka:
  instance.appGroupName: 'sample'
  client:
    serviceUrl.defaultZone: http://localhost:9000/eureka/
